<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // Kue Tradisional (category_id: 1) - seller bu_sari (id: 2)
            [
                'category_id' => 1,
                'seller_id'   => 2,
                'name'        => 'Kue Lapis Legit',
                'slug'        => 'kue-lapis-legit',
                'description' => 'Kue lapis legit original resep nenek, terbuat dari 30 lapisan tipis dengan rasa manis dan harum rempah. Cocok untuk oleh-oleh dan perayaan.',
                'price'       => 85000,
                'stock'       => 20,
                'weight'      => 500,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 1,
                'seller_id'   => 2,
                'name'        => 'Klepon Mranggen',
                'slug'        => 'klepon-mranggen',
                'description' => 'Klepon khas Mranggen dengan isian gula merah melimpah, dibalut kelapa parut segar. Dibuat setiap pagi untuk menjaga kesegarannya.',
                'price'       => 15000,
                'stock'       => 50,
                'weight'      => 200,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 1,
                'seller_id'   => 3,
                'name'        => 'Onde-onde Wijen',
                'slug'        => 'onde-onde-wijen',
                'description' => 'Onde-onde lembut dengan lapisan wijen yang banyak dan isian kacang hijau manis. Digoreng fresh setiap hari.',
                'price'       => 20000,
                'stock'       => 40,
                'weight'      => 250,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            // Snack Gurih (category_id: 2) - seller pak_budi (id: 3)
            [
                'category_id' => 2,
                'seller_id'   => 3,
                'name'        => 'Keripik Tempe Pedas',
                'slug'        => 'keripik-tempe-pedas',
                'description' => 'Keripik tempe renyah dengan bumbu pedas level 1-5. Terbuat dari tempe pilihan, digoreng dengan minyak bersih tanpa pengawet.',
                'price'       => 25000,
                'stock'       => 100,
                'weight'      => 150,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 2,
                'seller_id'   => 3,
                'name'        => 'Rempeyek Kacang',
                'slug'        => 'rempeyek-kacang',
                'description' => 'Rempeyek kacang tanah renyah dengan bumbu yang gurih dan krenyes. Pas untuk teman makan nasi atau camilan sore hari.',
                'price'       => 18000,
                'stock'       => 80,
                'weight'      => 100,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            // Minuman Tradisional (category_id: 3) - seller mbak_rina (id: 6)
            [
                'category_id' => 3,
                'seller_id'   => 6,
                'name'        => 'Wedang Uwuh Sachet',
                'slug'        => 'wedang-uwuh-sachet',
                'description' => 'Wedang uwuh khas Jogja dalam kemasan sachet praktis. Berisi kayu manis, cengkeh, kapulaga, dan rempah pilihan. 10 sachet per pack.',
                'price'       => 35000,
                'stock'       => 60,
                'weight'      => 100,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 3,
                'seller_id'   => 6,
                'name'        => 'Jahe Merah Instan',
                'slug'        => 'jahe-merah-instan',
                'description' => 'Jahe merah instan bubuk hangat untuk minuman kesehatan. Tanpa pengawet, tanpa pewarna. 10 sachet per box.',
                'price'       => 28000,
                'stock'       => 75,
                'weight'      => 80,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            // Makanan Berat (category_id: 4)
            [
                'category_id' => 4,
                'seller_id'   => 2,
                'name'        => 'Bandeng Presto Mranggen',
                'slug'        => 'bandeng-presto-mranggen',
                'description' => 'Bandeng presto khas Mranggen, tulangnya lunak dan dagingnya gurih lezat. Bisa langsung dimakan atau digoreng terlebih dahulu.',
                'price'       => 65000,
                'stock'       => 30,
                'weight'      => 800,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            // Oleh-oleh (category_id: 5)
            [
                'category_id' => 5,
                'seller_id'   => 6,
                'name'        => 'Hampers Jajan Mranggen',
                'slug'        => 'hampers-jajan-mranggen',
                'description' => 'Paket hampers berisi aneka jajan khas Mranggen: klepon, onde-onde, keripik tempe, dan wedang uwuh. Cocok untuk hadiah.',
                'price'       => 150000,
                'stock'       => 15,
                'weight'      => 1500,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            // Kue Kering (category_id: 6)
            [
                'category_id' => 6,
                'seller_id'   => 3,
                'name'        => 'Nastar Nanas Premium',
                'slug'        => 'nastar-nanas-premium',
                'description' => 'Nastar nanas dengan selai nanas asli yang manis dan lembut. Adonan kue yang renyah dan tidak terlalu manis. Isi 30 pcs per toples.',
                'price'       => 75000,
                'stock'       => 25,
                'weight'      => 400,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 6,
                'seller_id'   => 2,
                'name'        => 'Putri Salju Kacang Mete',
                'slug'        => 'putri-salju-kacang-mete',
                'description' => 'Kue putri salju lembur dengan isian kacang mete pilihan, dibalut gula halus yang meleleh di mulut. Isi 25 pcs per toples.',
                'price'       => 80000,
                'stock'       => 20,
                'weight'      => 350,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 2,
                'seller_id'   => 6,
                'name'        => 'Krupuk Rambak Sapi',
                'slug'        => 'krupuk-rambak-sapi',
                'description' => 'Krupuk rambak kulit sapi yang renyah dan gurih. Tanpa pengawet, diproses secara higienis. 200 gram per bungkus.',
                'price'       => 45000,
                'stock'       => 50,
                'weight'      => 200,
                'image'       => null,
                'status'      => 'active',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('products')->insertBatch($products);
    }
}
